name: Run unit tests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test_on_wasm:
    name: Build and Test on WebAssembly
    runs-on: Ubuntu-18.04
    container:
      image: ghcr.io/swiftwasm/carton:latest
    steps:
      - uses: actions/checkout@v2
      - run: carton test
  test_on_macOS:
    name: Build and Test on Native
    strategy:
      matrix:
        swift-version: ["4.2", "5.0", "5.1", "5.2", "5.3"]
        os: [macOS-10.15, Ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup swiftenv
        run: |
          git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
          export SWIFTENV_ROOT="$HOME/.swiftenv"
          export PATH="$SWIFTENV_ROOT/bin:$PATH"
          eval "$(swiftenv init -)"
          echo "$PATH" >> $GITHUB_PATH
      - name: Install Swift
        run: swiftenv install "${{ matrix.swift-version }}" --skip-existing
      - run: swift --version
      - run: swift test
